# Generated by Django 4.2.1 on 2023-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=51)),
                ('singer_name', models.CharField(max_length=50)),
                ('song_image', models.ImageField(upload_to='image')),
                ('song_audio', models.FileField(upload_to='song')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
